// src/components/CopyButton.tsx
import { useEffect, useRef, useState } from 'react';

async function writeClipboard(text: string): Promise<void> {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }
  // Fallback for insecure contexts.
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.setAttribute('readonly', '');
  ta.style.position = 'fixed';
  ta.style.opacity = '0';
  document.body.appendChild(ta);
  ta.select();
  document.execCommand('copy');
  ta.remove();
}

export function CopyButton({ text, label = 'Copy code' }: { text: string; label?: string }) {
  const [status, setStatus] = useState<'idle' | 'copied' | 'error'>('idle');
  const timer = useRef<ReturnType<typeof setTimeout>>(undefined);

  useEffect(() => () => clearTimeout(timer.current), []);

  const onClick = async () => {
    try {
      await writeClipboard(text);
      setStatus('copied');
    } catch {
      setStatus('error');
    }
    clearTimeout(timer.current);
    timer.current = setTimeout(() => setStatus('idle'), 1500);
  };

  return (
    <button type="button" className="btn btn-small copy-btn" onClick={onClick} aria-label={label}>
      <span aria-hidden="true">{status === 'copied' ? 'Copied!' : status === 'error' ? 'Failed' : 'Copy'}</span>
      <span className="visually-hidden" role="status">
        {status === 'copied' ? 'Copied to clipboard' : status === 'error' ? 'Copy failed' : ''}
      </span>
    </button>
  );
}

// vue/src/components/CopyButton.vue
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue';

const props = withDefaults(defineProps<{ text: string; label?: string }>(), { label: 'Copy code' });
const status = ref<'idle' | 'copied' | 'error'>('idle');
let timer: ReturnType<typeof setTimeout> | undefined;
onBeforeUnmount(() => clearTimeout(timer));

async function writeClipboard(text: string): Promise<void> {
  if (navigator.clipboard?.writeText) return navigator.clipboard.writeText(text);
  const ta = document.createElement('textarea'); // fallback for insecure contexts
  ta.value = text;
  ta.setAttribute('readonly', '');
  ta.style.cssText = 'position:fixed;opacity:0';
  document.body.appendChild(ta);
  ta.select();
  document.execCommand('copy');
  ta.remove();
}

async function copy() {
  try {
    await writeClipboard(props.text);
    status.value = 'copied';
  } catch {
    status.value = 'error';
  }
  clearTimeout(timer);
  timer = setTimeout(() => (status.value = 'idle'), 1500);
}
</script>

<template>
  <button type="button" class="btn btn-small copy-btn" :aria-label="label" @click="copy">
    <span aria-hidden="true">{{ status === 'copied' ? 'Copied!' : status === 'error' ? 'Failed' : 'Copy' }}</span>
    <span class="visually-hidden" role="status">
      {{ status === 'copied' ? 'Copied to clipboard' : status === 'error' ? 'Copy failed' : '' }}
    </span>
  </button>
</template>
