// src/App.tsx
import { useDeferredValue, useEffect, useMemo, useRef, useState } from 'react';
import { ENTRIES, SECTIONS } from './content';
import type { Entry, SectionId } from './content/types';
import { EntryCard } from './components/EntryCard';
import { SearchBar } from './components/SearchBar';
import { Sidebar } from './components/Sidebar';
import { buildIndex, search } from './lib/search';
import { useHash } from './lib/useHash';
import { useTheme } from './lib/useTheme';

export interface AppProps {
  entries?: readonly Entry[];
}

export function App({ entries = ENTRIES }: AppProps) {
  const { theme, toggle } = useTheme();
  const [query, setQuery] = useState('');
  const deferredQuery = useDeferredValue(query);
  const [navOpen, setNavOpen] = useState(false);
  const hash = useHash();
  const searchRef = useRef<HTMLInputElement>(null);
  const navToggleRef = useRef<HTMLButtonElement>(null);

  const index = useMemo(() => buildIndex(entries), [entries]);
  const results = useMemo(() => search(index, deferredQuery), [index, deferredQuery]);

  const grouped = useMemo(() => {
    const map = new Map<SectionId, Entry[]>();
    for (const e of results) {
      const list = map.get(e.section);
      if (list) list.push(e);
      else map.set(e.section, [e]);
    }
    return map;
  }, [results]);

  // "/" focuses search from anywhere that isn't already a text field.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== '/' || e.ctrlKey || e.metaKey || e.altKey) return;
      const t = e.target as HTMLElement | null;
      if (t && (t.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName))) return;
      e.preventDefault();
      searchRef.current?.focus();
      searchRef.current?.select();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  // Escape closes the mobile nav and returns focus to its toggle.
  useEffect(() => {
    if (!navOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== 'Escape') return;
      setNavOpen(false);
      navToggleRef.current?.focus();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [navOpen]);

  // Deep link: if the target is hidden by the current search, clear the search first.
  const hashTargetsEntry = entries.some((e) => e.id === hash);
  const hashHidden = hashTargetsEntry && !results.some((e) => e.id === hash);
  useEffect(() => {
    if (hashHidden) setQuery('');
  }, [hashHidden, hash]);

  useEffect(() => {
    if (!hash || hashHidden) return;
    const el = document.getElementById(hash);
    if (!el) return;
    el.scrollIntoView?.({ block: 'start' });
    if (hashTargetsEntry) el.focus({ preventScroll: true });
  }, [hash, hashHidden, hashTargetsEntry]);

  const counts = useMemo(() => {
    const c = {} as Record<SectionId, number>;
    for (const s of SECTIONS) c[s.id] = grouped.get(s.id)?.length ?? 0;
    return c;
  }, [grouped]);

  return (
    <div className="app">
      <a className="skip-link" href="#main">
        Skip to content
      </a>
      <header className="topbar">
        <button
          ref={navToggleRef}
          type="button"
          className="btn nav-toggle"
          aria-expanded={navOpen}
          aria-controls="sidebar"
          onClick={() => setNavOpen((o) => !o)}
        >
          <span aria-hidden="true">☰</span>
          <span className="visually-hidden">Sections</span>
        </button>
        <h1 className="brand">
          <a href="#">TS + React Cheat Sheet</a>
        </h1>
        <SearchBar ref={searchRef} value={query} onChange={setQuery} resultCount={results.length} total={entries.length} />
        <button
          type="button"
          className="btn theme-toggle"
          onClick={toggle}
          aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`}
        >
          <span aria-hidden="true">{theme === 'dark' ? '☀' : '☾'}</span>
        </button>
      </header>

      <div className="layout">
        <Sidebar open={navOpen} counts={counts} onNavigate={() => setNavOpen(false)} />
        <main id="main" className="content" tabIndex={-1}>
          {results.length === 0 && (
            <p className="empty">
              No entries match <strong>“{deferredQuery}”</strong>.{' '}
              <button type="button" className="btn btn-small" onClick={() => setQuery('')}>
                Clear search
              </button>
            </p>
          )}
          {SECTIONS.map((section) => {
            const list = grouped.get(section.id);
            if (!list) return null;
            return (
              <section key={section.id} id={`section-${section.id}`} className="section" aria-labelledby={`h-${section.id}`}>
                <h2 id={`h-${section.id}`}>
                  {section.title} <span className="count">{list.length}</span>
                </h2>
                {!deferredQuery && <p className="blurb">{section.blurb}</p>}
                {list.map((entry) => (
                  <EntryCard key={entry.id} entry={entry} theme={theme} active={entry.id === hash} />
                ))}
              </section>
            );
          })}
        </main>
      </div>
    </div>
  );
}

// vue/src/App.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, useTemplateRef, watch } from 'vue';
import { refDebounced } from './lib/refDebounced';
import { ENTRIES, SECTIONS } from './content';
import type { Entry, SectionId } from './content/types';
import EntryCard from './components/EntryCard.vue';
import SearchBar from './components/SearchBar.vue';
import SideNav from './components/SideNav.vue';
import { buildIndex, search } from './lib/search';
import { useHash } from './lib/useHash';
import { useTheme } from './lib/useTheme';

const props = withDefaults(defineProps<{ entries?: readonly Entry[] }>(), { entries: () => ENTRIES });

const { theme, toggle } = useTheme();
const query = ref('');
// Typing stays responsive while 100+ cards filter: search a briefly debounced copy.
const settledQuery = refDebounced(query, 60);
const navOpen = ref(false);
const hash = useHash();
const searchBar = useTemplateRef<InstanceType<typeof SearchBar>>('searchBar');
const navToggle = useTemplateRef<HTMLButtonElement>('navToggle');

const index = computed(() => buildIndex(props.entries));
const results = computed(() => search(index.value, settledQuery.value));
const grouped = computed(() => Map.groupBy(results.value, (e) => e.section));
const counts = computed(() => {
  const c = {} as Record<SectionId, number>;
  for (const s of SECTIONS) c[s.id] = grouped.value.get(s.id)?.length ?? 0;
  return c;
});

// "/" focuses search from anywhere that isn't already a text field; Escape closes the mobile nav.
function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape' && navOpen.value) {
    navOpen.value = false;
    navToggle.value?.focus();
    return;
  }
  if (e.key !== '/' || e.ctrlKey || e.metaKey || e.altKey) return;
  const t = e.target as HTMLElement | null;
  if (t && (t.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName))) return;
  e.preventDefault();
  searchBar.value?.focus();
}
onMounted(() => window.addEventListener('keydown', onKeydown));
onBeforeUnmount(() => window.removeEventListener('keydown', onKeydown));

// Deep link: clear a search that hides the target, then scroll to and focus it.
watch(
  [hash, results],
  async ([h]) => {
    if (!h) return;
    const isEntry = props.entries.some((e) => e.id === h);
    if (isEntry && !results.value.some((e) => e.id === h)) {
      query.value = '';
      settledQuery.flush();
      return;
    }
    await nextTick();
    const el = document.getElementById(h);
    el?.scrollIntoView?.({ block: 'start' });
    if (isEntry) el?.focus({ preventScroll: true });
  },
  { immediate: true },
);
</script>

<template>
  <div class="app">
    <a class="skip-link" href="#main">Skip to content</a>
    <header class="topbar">
      <button
        ref="navToggle"
        type="button"
        class="btn nav-toggle"
        :aria-expanded="navOpen"
        aria-controls="sidebar"
        @click="navOpen = !navOpen"
      >
        <span aria-hidden="true">☰</span>
        <span class="visually-hidden">Sections</span>
      </button>
      <h1 class="brand"><a href="#">Vue 3 Cheat Sheet</a></h1>
      <SearchBar ref="searchBar" v-model="query" :result-count="results.length" :total="entries.length" />
      <button
        type="button"
        class="btn theme-toggle"
        :aria-label="`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`"
        @click="toggle"
      >
        <span aria-hidden="true">{{ theme === 'dark' ? '☀' : '☾' }}</span>
      </button>
    </header>

    <div class="layout">
      <SideNav :open="navOpen" :counts="counts" @navigate="navOpen = false" />
      <main id="main" class="content" tabindex="-1">
        <p v-if="results.length === 0" class="empty">
          No entries match <strong>“{{ settledQuery }}”</strong>.
          <button type="button" class="btn btn-small" @click="query = ''">Clear search</button>
        </p>
        <template v-for="section in SECTIONS" :key="section.id">
          <section
            v-if="grouped.get(section.id)"
            :id="`section-${section.id}`"
            class="section"
            :aria-labelledby="`h-${section.id}`"
          >
            <h2 :id="`h-${section.id}`">
              {{ section.title }} <span class="count">{{ grouped.get(section.id)?.length }}</span>
            </h2>
            <p v-if="!settledQuery" class="blurb">{{ section.blurb }}</p>
            <EntryCard
              v-for="entry in grouped.get(section.id)"
              :key="entry.id"
              :entry="entry"
              :active="entry.id === hash"
            />
          </section>
        </template>
      </main>
    </div>
  </div>
</template>
