// vue/src/demos/timing/TimelineVisualizer.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, useId, watch } from 'vue';
import { laneWindows, useTimeline, type LaneKey, type TimelineEvent } from './useTimeline';

const LANES: readonly { key: LaneKey; label: string; hint: string }[] = [
  { key: 'raw', label: 'Raw events', hint: 'every click / keystroke' },
  { key: 'trailing', label: 'debounce · trailing', hint: 'once, after the burst goes quiet' },
  { key: 'leading', label: 'debounce · leading', hint: 'instantly, then ignores the burst' },
  { key: 'both', label: 'debounce · leading + trailing', hint: 'instantly and after the burst' },
  { key: 'throttle', label: 'throttle', hint: 'at most once per wait, steady rhythm' },
  { key: 'raf', label: 'rAF throttle', hint: 'at most once per frame (~16 ms)' },
];
const WINDOW_MS = 6000;
const BURST: readonly number[] = [
  ...Array.from({ length: 12 }, (_, i) => i * 70), // fast burst
  ...Array.from({ length: 5 }, (_, i) => 1800 + i * 240), // slower taps
  3600, // lone click
];

const { lanes, initialWait = 300 } = defineProps<{
  /** Which lanes to show (defaults to all). `raw` is always shown. */
  lanes?: readonly LaneKey[];
  initialWait?: number;
}>();

const wait = ref(initialWait);
const { events, fire, clear } = useTimeline(wait);
const paused = ref(false);
const now = ref(performance.now());
const origin = ref(performance.now());
const text = ref('');
const waitId = useId();
let counter = 0;
let burstTimers: ReturnType<typeof setTimeout>[] = [];
let frame: number | undefined;

const shown = computed(() => LANES.filter((l) => l.key === 'raw' || !lanes || lanes.includes(l.key)));
// Keep scrolling until every limiter has had time to settle, then freeze so the burst can be studied.
const settleAt = computed(() => (events.value.at(-1)?.t ?? -Infinity) + Math.max(wait.value * 2, 800));
const live = computed(() => !paused.value && now.value < settleAt.value);

function tick() {
  frame = undefined;
  now.value = performance.now();
  if (!paused.value && now.value < settleAt.value) frame = requestAnimationFrame(tick);
}
function ensureLoop() {
  if (frame === undefined && !paused.value) frame = requestAnimationFrame(tick);
}
watch([events, paused], ensureLoop);
onBeforeUnmount(() => {
  if (frame !== undefined) cancelAnimationFrame(frame);
  burstTimers.forEach(clearTimeout);
});

const onMash = () => fire(`click #${++counter}`);
const onType = () => fire(JSON.stringify(text.value));
function playBurst() {
  burstTimers.forEach(clearTimeout);
  burstTimers = BURST.map((delay, i) => setTimeout(() => fire(`burst #${i + 1}`), delay));
}
function onClear() {
  burstTimers.forEach(clearTimeout);
  counter = 0;
  clear();
  origin.value = now.value = performance.now();
}

const start = computed(() => now.value - WINDOW_MS);
const pct = (t: number) => ((t - start.value) / WINDOW_MS) * 100;
const ticks = computed(() => {
  const out: number[] = [];
  for (let s = Math.max(0, Math.ceil((start.value - origin.value) / 1000)); origin.value + s * 1000 <= now.value; s++) out.push(s);
  return out;
});
const byLane = computed(() => Map.groupBy(events.value, (e) => e.lane));
const laneEvents = (k: LaneKey): TimelineEvent[] => byLane.value.get(k) ?? [];
const visible = (e: TimelineEvent) => e.t >= start.value - 200 && e.t <= now.value + 1;
const windowsFor = (k: LaneKey) =>
  laneWindows(events.value, k)
    .filter(([s, e]) => e >= start.value && s <= now.value)
    .map(([s, e]) => {
      const left = Math.max(0, pct(s));
      return { key: s, left, width: Math.max(0, pct(Math.min(e, now.value)) - left) };
    });
</script>

<template>
  <div class="tv">
    <div class="tv-controls">
      <button type="button" class="btn btn-primary tv-mash" @click="onMash">Mash me</button>
      <label class="tv-field">
        <span>Type here</span>
        <input v-model="text" type="text" placeholder="search…" @input="onType" />
      </label>
      <button type="button" class="btn" @click="playBurst">Play sample burst</button>
      <label class="tv-field tv-wait">
        <span>wait <output :for="waitId">{{ wait }} ms</output></span>
        <input :id="waitId" v-model.number="wait" type="range" min="50" max="1500" step="50" />
      </label>
      <button type="button" class="btn" :aria-pressed="paused" @click="paused = !paused">
        {{ paused ? 'Resume' : 'Pause' }}
      </button>
      <button type="button" class="btn" @click="onClear">Clear</button>
    </div>

    <div class="tv-status" aria-hidden="true">
      <span class="tv-dot" :class="{ 'tv-dot-live': live }" />
      {{ paused ? 'paused' : live ? 'live' : 'frozen — interact to continue' }}
      <span class="tv-scale">
        <span class="tv-scale-bar" :style="{ width: `${(wait / WINDOW_MS) * 100}%` }" />
        wait = {{ wait }} ms
      </span>
    </div>

    <div class="tv-grid" role="group" :aria-label="`Timeline of the last ${WINDOW_MS / 1000} seconds`">
      <div v-for="lane in shown" :key="lane.key" class="tv-lane" :data-lane="lane.key">
        <div class="tv-label">
          <strong>{{ lane.label }}</strong>
          <span class="tv-hint">{{ lane.hint }}</span>
        </div>
        <div
          class="tv-track"
          role="img"
          :aria-label="`${lane.label}: ${laneEvents(lane.key).length} ${laneEvents(lane.key).length === 1 ? 'call' : 'calls'}`"
        >
          <span v-for="s in ticks" :key="`t${s}`" class="tv-tick" :style="{ left: `${pct(origin + s * 1000)}%` }" />
          <span
            v-for="w in windowsFor(lane.key)"
            :key="`w${w.key}`"
            class="tv-window"
            :style="{ left: `${w.left}%`, width: `${w.width}%` }"
          />
          <span
            v-for="(e, i) in laneEvents(lane.key).filter(visible)"
            :key="`${e.t}-${i}`"
            class="tv-mark"
            :style="{ left: `${pct(e.t)}%` }"
            :title="e.value"
          />
        </div>
        <div class="tv-stat">
          <span class="tv-count" :data-testid="`count-${lane.key}`">{{ laneEvents(lane.key).length }}</span>
          <span class="tv-last" :title="laneEvents(lane.key).at(-1)?.value">{{ laneEvents(lane.key).at(-1)?.value ?? '—' }}</span>
        </div>
      </div>
      <div class="tv-axis" aria-hidden="true">
        <span v-for="s in ticks" :key="s" :style="{ left: `${pct(origin + s * 1000)}%` }">{{ s }}s</span>
      </div>
    </div>
    <p class="tv-legend">
      Dots are calls; shaded bars show when a debounce timer is armed (resets on every raw event) or when
      throttle is locked out. Try a fast burst, then slow taps just under and just over the wait.
    </p>
  </div>
</template>

<style src="./TimelineVisualizer.css"></style>

// src/demos/timing/TimelineVisualizer.tsx
import { useEffect, useId, useRef, useState } from 'react';
import { laneWindows, useTimeline, type LaneKey, type TimelineEvent } from './useTimeline';
import './TimelineVisualizer.css';

interface LaneInfo {
  key: LaneKey;
  label: string;
  hint: string;
}

export const LANES: readonly LaneInfo[] = [
  { key: 'raw', label: 'Raw events', hint: 'every click / keystroke' },
  { key: 'trailing', label: 'debounce · trailing', hint: 'once, after the burst goes quiet' },
  { key: 'leading', label: 'debounce · leading', hint: 'instantly, then ignores the burst' },
  { key: 'both', label: 'debounce · leading + trailing', hint: 'instantly and after the burst' },
  { key: 'throttle', label: 'throttle', hint: 'at most once per wait, steady rhythm' },
  { key: 'raf', label: 'rAF throttle', hint: 'at most once per frame (~16 ms)' },
];

const WINDOW_MS = 6000;
const BURST: readonly number[] = [
  ...Array.from({ length: 12 }, (_, i) => i * 70), // fast burst
  ...Array.from({ length: 5 }, (_, i) => 1800 + i * 240), // slower taps
  3600, // lone click
];

export interface TimelineVisualizerProps {
  /** Which lanes to show (defaults to all). `raw` is always shown. */
  lanes?: readonly LaneKey[];
  initialWait?: number;
}

export function TimelineVisualizer({ lanes, initialWait = 300 }: TimelineVisualizerProps) {
  const [wait, setWait] = useState(initialWait);
  const { events, fire, clear, version } = useTimeline(wait);
  const [paused, setPaused] = useState(false);
  const [now, setNow] = useState(() => performance.now());
  const [origin, setOrigin] = useState(() => performance.now());
  const counter = useRef(0);
  const burstTimers = useRef<ReturnType<typeof setTimeout>[]>([]);
  const [text, setText] = useState('');
  const ids = useId();

  const shown = LANES.filter((l) => l.key === 'raw' || !lanes || lanes.includes(l.key));
  const lastEvent = events.at(-1)?.t ?? -Infinity;
  // Keep scrolling until every limiter has had time to settle, then freeze so the burst can be studied.
  const settleAt = lastEvent + Math.max(wait * 2, 800);
  const live = !paused && now < settleAt;

  useEffect(() => {
    if (paused) return;
    let frame = requestAnimationFrame(function tick() {
      const t = performance.now();
      setNow(t);
      if (t < settleAt) frame = requestAnimationFrame(tick);
    });
    return () => cancelAnimationFrame(frame);
  }, [paused, settleAt, version]);

  useEffect(() => () => burstTimers.current.forEach(clearTimeout), []);

  const emit = (value: string) => fire(value);
  const onMash = () => emit(`click #${++counter.current}`);
  const playBurst = () => {
    burstTimers.current.forEach(clearTimeout);
    burstTimers.current = BURST.map((delay, i) => setTimeout(() => emit(`burst #${i + 1}`), delay));
  };
  const onClear = () => {
    burstTimers.current.forEach(clearTimeout);
    counter.current = 0;
    clear();
    const t = performance.now();
    setOrigin(t);
    setNow(t);
  };

  const start = now - WINDOW_MS;
  const pct = (t: number) => ((t - start) / WINDOW_MS) * 100;
  const visible = (t: number) => t >= start - 200 && t <= now + 1;

  const ticks: number[] = [];
  for (let s = Math.ceil((start - origin) / 1000); origin + s * 1000 <= now; s++) {
    if (s >= 0) ticks.push(s);
  }

  const byLane = new Map<LaneKey, TimelineEvent[]>();
  for (const e of events) {
    const list = byLane.get(e.lane);
    if (list) list.push(e);
    else byLane.set(e.lane, [e]);
  }

  return (
    <div className="tv">
      <div className="tv-controls">
        <button type="button" className="btn btn-primary tv-mash" onClick={onMash}>
          Mash me
        </button>
        <label className="tv-field">
          <span>Type here</span>
          <input
            type="text"
            value={text}
            onChange={(e) => {
              setText(e.target.value);
              emit(JSON.stringify(e.target.value));
            }}
            placeholder="search…"
          />
        </label>
        <button type="button" className="btn" onClick={playBurst}>
          Play sample burst
        </button>
        <label className="tv-field tv-wait">
          <span>
            wait <output htmlFor={`${ids}-wait`}>{wait} ms</output>
          </span>
          <input
            id={`${ids}-wait`}
            type="range"
            min={50}
            max={1500}
            step={50}
            value={wait}
            onChange={(e) => setWait(Number(e.target.value))}
          />
        </label>
        <button type="button" className="btn" aria-pressed={paused} onClick={() => setPaused((p) => !p)}>
          {paused ? 'Resume' : 'Pause'}
        </button>
        <button type="button" className="btn" onClick={onClear}>
          Clear
        </button>
      </div>

      <div className="tv-status" aria-hidden="true">
        <span className={`tv-dot${live ? ' tv-dot-live' : ''}`} />
        {paused ? 'paused' : live ? 'live' : 'frozen — interact to continue'}
        <span className="tv-scale">
          <span className="tv-scale-bar" style={{ width: `${(wait / WINDOW_MS) * 100}%` }} />
          wait = {wait} ms
        </span>
      </div>

      <div className="tv-grid" role="group" aria-label={`Timeline of the last ${WINDOW_MS / 1000} seconds`}>
        {shown.map((lane) => {
          const laneEvents = byLane.get(lane.key) ?? [];
          const windows = laneWindows(events, lane.key).filter(([s, e]) => e >= start && s <= now);
          const last = laneEvents.at(-1);
          return (
            <div key={lane.key} className="tv-lane" data-lane={lane.key}>
              <div className="tv-label">
                <strong>{lane.label}</strong>
                <span className="tv-hint">{lane.hint}</span>
              </div>
              <div
                className="tv-track"
                role="img"
                aria-label={`${lane.label}: ${laneEvents.length} ${laneEvents.length === 1 ? 'call' : 'calls'}`}
              >
                {ticks.map((s) => (
                  <span key={s} className="tv-tick" style={{ left: `${pct(origin + s * 1000)}%` }} />
                ))}
                {windows.map(([s, e]) => (
                  <span
                    key={s}
                    className="tv-window"
                    style={{ left: `${Math.max(0, pct(s))}%`, width: `${Math.max(0, pct(Math.min(e, now)) - Math.max(0, pct(s)))}%` }}
                  />
                ))}
                {laneEvents.filter((e) => visible(e.t)).map((e, i) => (
                  <span key={`${e.t}-${i}`} className="tv-mark" style={{ left: `${pct(e.t)}%` }} title={e.value} />
                ))}
              </div>
              <div className="tv-stat">
                <span className="tv-count" data-testid={`count-${lane.key}`}>
                  {laneEvents.length}
                </span>
                <span className="tv-last" title={last?.value}>
                  {last?.value ?? '—'}
                </span>
              </div>
            </div>
          );
        })}
        <div className="tv-axis" aria-hidden="true">
          {ticks.map((s) => (
            <span key={s} style={{ left: `${pct(origin + s * 1000)}%` }}>
              {s}s
            </span>
          ))}
        </div>
      </div>
      <p className="tv-legend">
        Dots are calls; shaded bars show when a debounce timer is armed (resets on every raw event) or when
        throttle is locked out. Try a fast burst, then slow taps just under and just over the wait.
      </p>
    </div>
  );
}

export const TimelineDemo = () => <TimelineVisualizer />;
export const TrailingDemo = () => <TimelineVisualizer lanes={['trailing']} />;
export const LeadingDemo = () => <TimelineVisualizer lanes={['leading']} />;
export const LeadingTrailingDemo = () => <TimelineVisualizer lanes={['leading', 'both', 'trailing']} />;
export const ThrottleDemo = () => <TimelineVisualizer lanes={['throttle', 'trailing']} />;
export const RafDemo = () => <TimelineVisualizer lanes={['raf', 'throttle']} initialWait={100} />;
