// src/snippets/react-features/Modal.tsx
import { useEffect, useId, type ReactNode } from 'react';
import { createPortal } from 'react-dom';

interface Props {
  open: boolean;
  title: string;
  onClose: () => void;
  children: ReactNode;
  container?: Element; // defaults to document.body (client only)
}

export function Modal({ open, title, onClose, children, container }: Props) {
  const titleId = useId();

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && onClose();
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  if (!open) return null;
  // Rendered into another DOM node (escapes overflow/z-index), but it stays in
  // the React tree: context flows and React events bubble to React ancestors.
  return createPortal(
    <div role="dialog" aria-modal="true" aria-labelledby={titleId}>
      <h2 id={titleId}>{title}</h2>
      {children}
      <button onClick={onClose}>Close</button>
    </div>,
    container ?? document.body,
  );
}

// vue/src/snippets/components/Modal.vue
<script setup lang="ts">
import { useId, useTemplateRef, watch } from 'vue';

const { title, inline = false } = defineProps<{ title: string; inline?: boolean }>();
const open = defineModel<boolean>('open', { default: false });
const titleId = useId();
const dialog = useTemplateRef('dialog');

// flush: 'post' runs after the DOM update, so the dialog exists when we focus it.
watch(open, (isOpen) => isOpen && dialog.value?.focus(), { flush: 'post' });
</script>

<template>
  <!-- Rendered at <body> to escape overflow/z-index of ancestors; `disabled` renders in place -->
  <Teleport to="body" :disabled="inline">
    <div v-if="open" class="modal-backdrop" @click.self="open = false">
      <div
        ref="dialog"
        class="modal"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="titleId"
        tabindex="-1"
        @keydown.esc="open = false"
      >
        <h2 :id="titleId">{{ title }}</h2>
        <slot />
        <button type="button" class="btn" @click="open = false">Close</button>
      </div>
    </div>
  </Teleport>
</template>
