// src/snippets/dom-a11y/NativeDialog.tsx
import { useEffect, useId, useRef, type ReactNode } from 'react';

interface Props { open: boolean; onClose: () => void; title: string; children: ReactNode }

// showModal() gives you for free: focus moved inside, Tab trapped (rest of page is
// inert), Escape closes, focus restored to the opener, ::backdrop, top layer (no z-index).
export function NativeDialog({ open, onClose, title, children }: Props) {
  const ref = useRef<HTMLDialogElement>(null);
  const titleId = useId();

  useEffect(() => {
    const dialog = ref.current;
    if (!dialog) return;
    if (open && !dialog.open) dialog.showModal(); // NOT `open` attribute: that's non-modal
    else if (!open && dialog.open) dialog.close();
  }, [open]);

  return (
    // `close` fires for Escape, form[method=dialog] and .close(): sync React state here.
    <dialog ref={ref} aria-labelledby={titleId} onClose={onClose}>
      <h2 id={titleId}>{title}</h2>
      {children}
      <button type="button" autoFocus onClick={() => ref.current?.close()}>Close</button>
    </dialog>
  );
}

// vue/src/snippets/dom-a11y/NativeDialog.vue
<script setup lang="ts">
import { useId, useTemplateRef, watch } from 'vue';

defineProps<{ title: string }>();
const open = defineModel<boolean>('open', { required: true });
const emit = defineEmits<{ close: [returnValue: string] }>();
const dialog = useTemplateRef('dialog');
const titleId = useId();

// State drives the DOM API; the native `close` event (Escape, .close()) syncs state back.
watch([open, dialog], ([isOpen, el]) => {
  if (!el || isOpen === el.open) return;
  if (isOpen) el.showModal(); // modal: focus trap, inert page, ::backdrop, top layer
  else el.close();
});
function onClose() {
  open.value = false;
  emit('close', dialog.value?.returnValue ?? '');
}
</script>

<template>
  <dialog ref="dialog" :aria-labelledby="titleId" @close="onClose">
    <h2 :id="titleId">{{ title }}</h2>
    <slot />
    <button type="button" autofocus @click="dialog?.close('cancel')">Cancel</button>
    <button type="button" @click="dialog?.close('confirm')">Confirm</button>
  </dialog>
</template>
